### ISSUE TITLE
Deadlock in Mysql

### ISSUE THREAD

**Issue by larsmeldgaard** [arnoldasgudas/Hangfire.MySqlStorage#18]
I get this error in the application lock on my server:

Is this an implementation problem of the MySql adaptor or something deeper ? It happens a few time every day but not related to specific events.

MySql.Data.MySqlClient.MySqlException (0x80004005): Deadlock found when trying to get lock; try restarting transaction
at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
at Hangfire.MySql.MySqlDistributedLock.AcquireLock(String resource, TimeSpan timeout)
at Hangfire.MySql.MySqlDistributedLock.Acquire()
at Hangfire.MySql.ExpirationManager.<>c__DisplayClass6.b__0(MySqlConnection connection) 

I have these details:
executing
INSERT INTO DistributedLock (Resource, CreatedAt) SELECT 'locks:schedulepoller', '2017-01-15 05:04:35.387605' FROM dual WHERE NOT EXISTS ( SELECT * FROM DistributedLock WHERE Resource = 'locks:schedulepoller' AND CreatedAt > '2017-01-15 05:03:35.387605')

executing
INSERT INTO DistributedLock (Resource, CreatedAt) SELECT 'expirationmanager', '2017-01-15 05:04:35.387605' FROM dual WHERE NOT EXISTS ( SELECT * FROM DistributedLock WHERE Resource = 'expirationmanager' AND CreatedAt > '2017-01-15 05:04:05.387605')

*** WE ROLL BACK TRANSACTION (2)

a key to the deadlock could be, that on the same server I have two instances of hangfire running. But in my view, deadlocks should not happen on a regular basis.

**Comment by xavierjefferson** [comment]
I'm experiencing this too.  It's really annoying in the Visual Studio IDE.

**Comment by ultravelocity** [comment]
We're seeing deadlocks as well. Anyone have any suggestions?

**Comment by jobou363** [comment]
I'm having also deadlock but I have I different exception :

Deadlock found when trying to get lock; try restarting transaction
MySql.Data.MySqlClient.MySqlException: Deadlock found when trying to get lock; try restarting transaction
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Hangfire.MySql.JobQueue.MySqlJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.MySql.MySqlStorageConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

**Comment by RunnicFusion** [comment]
Any solution in this?

**Comment by JuhBoy** [comment]
it would be great if someone had a solution, is this error occurs in production as well ?

**Comment by dilbert11** [comment]
I am also getting deadlock at 
Hangfire.MySql.JobQueue.MySqlJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)

Context: I'm running hangfire.io MySQL edition on my local developer laptop, so only one server in action.  I have 7 recurring jobs which run on a crontab schedule of every 5 minutes.  I occasionally get deadlocks (a couple times a week).

Looking at the source code I found it looks like there are multiple connections created rather than reused.  In the code below "CreateAndOpenConnection" creates a new connection, but then so does "new MySqlDistributedLock" just a few lines below.


```
                connection = _storage.CreateAndOpenConnection();               
                try
                {
                    using (new MySqlDistributedLock(_storage, "JobQueue", TimeSpan.FromSeconds(30)))
```

Checking MySQL server I see many connections created, so that could be due to the above potentially non-optimal code.  I think the CreateAndOpenConnection call should add the connection to the _existingConnection variable after creating a new one.  This would allow it to be reused, though I don' t know if that will cause any side effects.

I waited until a got a deadlock and then checked mysql for the last deadlock details using: 
mysql > SHOW ENGINE INNODB STATUS;

This is an excerpt from the output:
LATEST DETECTED DEADLOCK
------------------------
2018-06-22 08:25:44 0x37c4
*** (1) TRANSACTION:
TRANSACTION 46603259, ACTIVE 0 sec updating or deleting
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 1
MySQL thread id 1177, OS thread handle 9016, query id 2365920 localhost 127.0.0.1 user1 updating
delete from JobQueue where Id = 3719
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 32 page no 4 n bits 80 index IX_JobQueue_QueueAndFetchedAt of table `hangfire`.`jobqueue` trx id 46603259 lock_mode X locks rec but n
ot gap waiting
Record lock, heap no 3 PHYSICAL RECORD: n_fields 3; compact format; info bits 0
 0: len 7; hex 64656661756c74; asc default;;
 1: len 8; hex 99a02ce640000000; asc   , @   ;;
 2: len 4; hex 80000e87; asc     ;;

*** (2) TRANSACTION:
TRANSACTION 46603262, ACTIVE 0 sec starting index read, thread declared inside InnoDB 1
mysql tables in use 1, locked 1
3 lock struct(s), heap size 1136, 2 row lock(s)
MySQL thread id 1158, OS thread handle 14276, query id 2365935 localhost 127.0.0.1 user1 Searching rows for update
update JobQueue set FetchedAt = UTC_TIMESTAMP(), FetchToken = 'daef8b91-ea7d-446e-95fb-6fadd1f0cdcf' where (FetchedAt is null or FetchedAt < DATE_ADD(UTC_TIMEST
AMP(), INTERVAL -1800 SECOND))    and Queue in ('default') LIMIT 1
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 32 page no 4 n bits 80 index IX_JobQueue_QueueAndFetchedAt of table `hangfire`.`jobqueue` trx id 46603262 lock_mode X locks rec but n
ot gap
Record lock, heap no 3 PHYSICAL RECORD: n_fields 3; compact format; info bits 0
 0: len 7; hex 64656661756c74; asc default;;
 1: len 8; hex 99a02ce640000000; asc   , @   ;;
 2: len 4; hex 80000e87; asc     ;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 32 page no 3 n bits 80 index PRIMARY of table `hangfire`.`jobqueue` trx id 46603262 lock_mode X locks rec but not gap waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 7; compact format; info bits 32
 0: len 4; hex 80000e87; asc     ;;
 1: len 6; hex 000002c71bfb; asc       ;;
 2: len 7; hex 2c000002d50110; asc ,      ;;
 3: len 4; hex 80037cf1; asc   | ;;
 4: len 7; hex 64656661756c74; asc default;;
 5: len 8; hex 99a02ce640000000; asc   , @   ;;
 6: len 30; hex 33363966346234642d366364662d343337332d626134302d646361663066; asc 369f4b4d-6cdf-4373-ba40-dcaf0f; (total 36 bytes);

*** WE ROLL BACK TRANSACTION (2)
------------

It appears the Dequeue call is deadlocked on calling 
   `delete from JobQueue where Id = 3719`
by another process/thread running
  ```
update JobQueue set FetchedAt = UTC_TIMESTAMP(), FetchToken = 'daef8b91-ea7d-446e-95fb-6fadd1f0cdcf' where (FetchedAt is null or FetchedAt < DATE_ADD(UTC_TIMEST
AMP(), INTERVAL -1800 SECOND))    and Queue in ('default') LIMIT 1
```

which could be locked by itself.

Note: This is the first time that I have looked at a deadlock in MySQL so I'm not experienced with interpreting deadlocks.

Would be interesting to know if others are also deadlocked on the same table / command.

**Comment by dilbert11** [comment]
I got another deadlock for a different table.  This time on table DistributedLock  on index GEN_CLUST_INDEX.  

------------------------
LATEST DETECTED DEADLOCK
------------------------
2018-06-26 03:05:05 0x2990
*** (1) TRANSACTION:
TRANSACTION 47896557, ACTIVE 0 sec inserting
mysql tables in use 2, locked 2
LOCK WAIT 4 lock struct(s), heap size 1136, 4 row lock(s)
MySQL thread id 3095, OS thread handle 15364, query id 6929669 localhost 127.0.0.1 user1 executing

INSERT INTO DistributedLock (Resource, CreatedAt)   SELECT 'job:236214:state-lock', '2018-06-26 09:05:05.443675'   FROM dual   WHERE NOT EXISTS ( SELECT * FROM DistributedLock WHERE Resource = 'job:236214:state-lock' AND CreatedAt > '2018-06-26 08:50:05.443675')
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 29 page no 3 n bits 72 index GEN_CLUST_INDEX of table `hangfire`.`distributedlock` trx id 47896557 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** (2) TRANSACTION:
TRANSACTION 47896558, ACTIVE 0 sec inserting, thread declared inside InnoDB 4997
mysql tables in use 2, locked 2
4 lock struct(s), heap size 1136, 4 row lock(s)
MySQL thread id 3092, OS thread handle 10640, query id 6929675 localhost 127.0.0.1 user1 executing

INSERT INTO DistributedLock (Resource, CreatedAt)   SELECT 'job:236216:state-lock', '2018-06-26 09:05:05.443675'   FROM dual   WHERE NOT EXISTS ( SELECT * FROM DistributedLock WHERE Resource = 'job:236216:state-lock' AND CreatedAt > '2018-06-26 08:50:05.443675')

*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 29 page no 3 n bits 72 index GEN_CLUST_INDEX of table `hangfire`.`distributedlock` trx id 47896558 lock mode S
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

Record lock, heap no 2 PHYSICAL RECORD: n_fields 5; compact format; info bits 0
 0: len 6; hex 00000016d955; asc      U;;
 1: len 6; hex 000002dad7dc; asc       ;;
 2: len 7; hex fc000001a70110; asc        ;;
 3: len 21; hex 6a6f623a3233363231323a73746174652d6c6f636b; asc job:236212:state-lock;;
 4: len 8; hex 99a0349145064b3a; asc   4 E K:;;

Record lock, heap no 3 PHYSICAL RECORD: n_fields 5; compact format; info bits 0
 0: len 6; hex 00000016d956; asc      V;;
 1: len 6; hex 000002dad7dd; asc       ;;
 2: len 7; hex fd000002110110; asc        ;;
 3: len 21; hex 6a6f623a3233363231313a73746174652d6c6f636b; asc job:236211:state-lock;;
 4: len 8; hex 99a0349145064b3a; asc   4 E K:;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 29 page no 3 n bits 72 index GEN_CLUST_INDEX of table `hangfire`.`distributedlock` trx id 47896558 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** WE ROLL BACK TRANSACTION (2)
-----------

When I check the indexes, I find none and MySQL documentation says GEN_CLUST_INDEX is the hidden, auto-generated index that is created when there are no index.  Recommendation by MySQL documentation is to create a primary index and when there are no unique fields (as the case is here). Primary index could be created on an auto-increment column.  I am adding a new column (int auto-increment) to the table as primary key.  Will see if that helps.

**Comment by julioapm** [comment]
Any news? @dilbert11 did your solution work?

**Comment by dilbert11** [comment]
I tried adding the ID to the index IX_JobQueue_QueueAndFetchedAt, and modified several other indexes in other tables adding more columns in hope that would work, but it didn't help to eliminate the deadlocks.  I tried to create a primary index on Handfire.DistributedLock to eliminate the GEN_CLUST_INDEX deadlock, but that didn't work either.  It comes down to what the MySQL documentation says which is that Deadlocks will occur and you have to handle them with retries.  I looked at the MySQL implementation of Handfire and compared it to the MSSQL version and found that MSSQL has a built-in functions/stored proc to get a lock, but the code also has a retry block if there is a lock/deadlock detected but the MySQL version doesn't do that.  I also found another MySQL implementation of Hangfire and I tried that one (with a few changes) but that one also suffers from deadlocks.  So the fix isn't going to be solved with changing indexes alone since you can't control the order MySQL performs implicit table row locks vs index lock on a table, so I think the fix needs to be done in code.  You need to detect the deadlock in the code, rollback, wait a small amount of time and retry the transaction hoping the other transaction completes or retries at a slightly different time than the other transactions participating in the deadlock.  The Hangfire for MSSQL has a pattern for that deadlock detection and retry, though that code base is quite different than this MySQL code base.  I haven't taken the time to fix the Hangfire code so I still have deadlocks.

**Comment by arnoldasgudas** [comment]
Fixed in https://www.nuget.org/packages/Hangfire.MySqlStorage/1.0.7

**Comment by yuzd** [comment]
15525222220

ktejlll5jlllklvlo
